spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: admin-dashboard
          uri: http://localhost:8040/
          predicates:
            - Path=/api/**
server:
  port:
    8060
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS