spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: admin-dashboard
          uri: http://localhost:8040
          predicates:
            - Path=/applications/**
        - id: twitch-api
          uri: http://localhost:8030
          predicates:
                     - Path=/twitch/**
server:
  port: 8060
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS