server:
  port: 8030

logging.level.org.hibernate:
        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: twitch-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
      properties.hibernate:
        generate_statistics: true
        jdbc.batch_size: 8
        order_inserts: true

      database: MYSQL
#      show-sql: true
#      use_sql_comments: true
#      format_sql: true
      hibernate:
        ddl-auto: update
  datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/twitchApi?createDatabaseIfNotExist=true
      username: root
      password:
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

